name: gibspons
description: "Introducing Gibspons, draft mails, track sponsorships, and manage negotiations, all in one place!"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  google_fonts: ^6.1.0
  gap: ^3.0.1
  font_awesome_flutter: ^10.7.0
  go_router: ^13.1.0
  intl: ^0.19.0
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  riverpod_lint: ^2.3.7
  custom_lint: ^0.5.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
    - assets/images/gibspons-logo.png
    - assets/images/gibspons-logo-dark.png
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
